services:
  products:
    container_name: products
    build: ./products
    volumes:
      - ./products/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  categories:
    container_name: categories
    build: ./categories
    volumes:
      - ./categories/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3015:3015"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  reviews:
    container_name: reviews
    build: ./reviews
    volumes:
      - ./reviews/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3016:3016"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  user:
    container_name: user
    build: ./user
    volumes:
      - ./user/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  microservice:
    container_name: microservice
    build: ./microservice
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"

networks:
  msexample:
    driver: bridge